# -*- coding: utf-8 -*-
"""
Created on Wed Jan  5 19:20:18 2022

@author: Sven
"""

import numpy as np


def generate_bxsf_file(filename, abinit, band_range=None):
    # modified from abipy iotools
    nband = abinit.nband
    ndivs = abinit.kpoints.mpdivs_shifts[0]
    nkpt = abinit.nkpt
    fermie = abinit.get_e0('fermie').to("Ha")
    energy_array = np.copy(
        abinit.eigens[0].to("Ha")
    ) - abinit.get_e0('fermie').to("Ha")
    # if band_range is not None:
    #     energy_array = energy_array[:,band_range[0]:band_range[1]]
    #     nband = band_range[1] - band_range[0]
    if band_range is None:
        band_range = (0, nband)

    file = open(filename, 'w')
    fw = file.write

    # Write the header.
    fw('BEGIN_INFO\n')
    fw('# Band-XCRYSDEN-Structure-File for Visualization of Fermi Surface\n')
    fw('# generated by the ABINIT package\n')
    fw('# NOTE: the first band is relative to spin-up electrons,\n')
    fw('#       the second band to spin-down electrons (if any) and so on \n')
    fw('#\n')
    fw('# Launch as: xcrysden --bxsf\n#\n')
    fw(' Fermi Energy: %f\n' % fermie)
    fw('END_INFO\n\n')
    fw(' BEGIN_BLOCK_BANDGRID_3D\n')
    fw('  band_energies\n')
    fw('  BEGIN_BANDGRID_3D_simple_example\n')

    fw('     '+str(band_range[1]-band_range[0]) + "\n")
    # Number of bands written.
    fw("     %d %d %d\n" % tuple(ndivs))
    # Number of division in the full BZ mesh.
    fw("     0.0 0.0 0.0\n")
    # Unshifted meshes are not supported.

    # Reciprocal lattice vectors in Ang^{-1}
    gcell = abinit.kpoints._reciprocal_lattice._matrix
    for i in range(3):
        fw('     %f %f %f\n' % tuple(gcell[i]))

    # energy_rel = energy_array + abs( np.amin(energy_array) )
    # energy_rel = energy_rel / np.amax(energy_rel)

    idx = 0
    for band in range(band_range[0], band_range[1]):
        idx += 1
        enes = energy_array[:, band]
        fw("  BAND: %d\n" % idx)
        row = "       "
        for k in range(nkpt):
            if k % ndivs[0] == 0 and k != 0:
                fw(row)
                fw('\n')
                row = "       "
                if k % (ndivs[0]*ndivs[1]) == 0:
                    fw('\n')
            row = row + (f"{enes[k]:.3f}  ")
        fw(row)

        fw("\n")

    fw('   END_BANDGRID_3D\n')
    fw(' END_BLOCK_BANDGRID_3D\n')
    file.flush()

    file.close()
